### PR TITLE
Color_Identification

### LINKED ISSUE #21: Color Identifier
### Is your feature request related to a problem? Please describe
A GUI application which can browse an image and tell you color name and HEX code for the cursor position/pin. GUI with random themes

### Describe the solution you'd like
a GUI application

### PR DESCRIPTION
**Pull request by Abubakrce19**
Resolved #21

## Description

The project folder contains 3 files:

1.) Color_detection.py – my main source code.
2.) sample.jpg – sample image for experimenting.
3.) Colors.csv – a file that contains my dataset.

Fixes #[ISSUENO]

## Dependencies

OpenCV
Pandas

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

#21 

## Screenshots of relevant screens
image
Note: Arrows in image are not part of Application GUI.

_Add screenshots of relevant screens_

## Developer's checklist

- [ ] My PR follows the style guidelines of this project
- [ ] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by Abubakrce19** [comment]
@bartick 
Please explain why this is spam??
So I can Improve !!
My all other merged prs are going in vain 😭for hacktoberfest
Please do something

**Comment by bartick** [comment]
you are not assigned to issue #21

**Comment by Abubakrce19** [comment]
> you are not assigned to issue #21

Sorry for that
I am new to open source 
Unspam me It will not happen again.

**Comment by Abubakrce19** [comment]
Bro they disqualified me from hactoberfest :/
The only chance is if you remove the spam label
so I can continue with this event!
Please do something

**Comment by Abubakrce19** [comment]
??

**Pull request closed without merging**
